### ISSUE TITLE
Keeps Crashing

### ISSUE THREAD

**Issue by cobracodess** [sergeyleschev/social-network#1]
I added all the necessary files, and I also added all the right firebase packages. Each time I try to view the canvas, it loads for a few seconds and then crashes. I tried running the build, and it was just a white screen. There are no errors. Anyone know why this is happening?

**Comment by sergeyleschev** [comment]
Good afternoon.
I just finished building the project locally. 
Everything is woking fine, registration works, and login as well. 

I tried to investigate your description.

Possible reasons:

1) Insufficient permissions granted for Firebase.
Below are the setup steps. If you encounter any difficulties, let me know, and I'll reset with more detailed screens on how Firebase should be configured for launch.

To launch the mobile app, you will need (steps from the repository description):
- Create a Firebase account (App). 
- Add the GoogleService-Info.plist file with your app data to the project (generated by Firebase).
- Enable Authentication in Firebase (Sign-in providers): Email/Password.
- Check and adjust the access rights of the Firestore Database (Cloud Firestore).

Firestore Rules:
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /{document=**} {
      allow read, write: if request.auth != null;
    }
  }
}
```

2) Check Package Dependencies in the project:
• abseil 0.20220203.2
• BoringSSL-GRPC 0.9.1
• Firebase 8.15.0
• GoogleAppMeasurement 8.15.0
• GoogleDataTransport 9.2.4
• GoogleUtilities 7.11.4
• gRPC 1.44.3-grpc
• GTMSessionFetcher 1.7.2
• Kingfisher 7.8.1
• leveldb 1.22.2
• nanopb 2.30908.0
• Promises 2.3.1
• SwiftProtobuf 1.22.0

3) If everything is correct, try XCode -> Product -> Clean build folder...
4) If there were changes to dependencies (may be), clean [DerivedData].
5) I used for testing: iPhone 14 Pro, iOS 16.4, XCode 14.3.1. Update to the latest version or reset the simulator if required.

Let me know if the steps above didn't help, and more help is needed.
